name: docker&aws

on:
  push:
    branches: [ main ]
    paths:
      
app/
pull_request:
  branches: [ main ]
  paths:
    
app/

env:
  IMAGE_NAME: fastapi
  IMAGE_TAG: latest
  FILES: docker-compose.yml

jobs:
  build:
    name: build and push Docker image
    runs-on: ubuntu-latest
    steps:
      
uses: actions/checkout@v4
name: Login to DockerHub
uses: docker/login-action@v3 
with:
  username: ${{ secrets.DH_USUARIO }}
  password: ${{ secrets.DH_TOKEN }}
name: Build and push Docker image
uses: docker/build-push-action@v5
with:
  context: .
  push: true 
  tags: ${{ secrets.DH_USUARIO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  aws:
    name: Deploy image to aws
    needs: build
    runs-on: ubuntu-latest
    steps:
    
uses: actions/checkout@v4
name: copy docker compose via ssh key
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.AMZ_IP }}
    username: ${{ secrets.AMZ_USUARIO }}
    port: 22 # ${{ secrets.PORT }}
    key: ${{ secrets.AMZ_CLAVE }}
    source: ${{ env.FILES }}
    target: /home/admin
name: script deploy docker services
uses: appleboy/ssh-action@v1.0.3
with:
  host: ${{ secrets.AMZ_IP }}
  username: ${{ secrets.AMZ_USUARIO }}
  key: ${{ secrets.AMZ_CLAVE }}
  port: 22  # ${{ secrets.PORT }}
  script: |
      sleep 30
      docker compose down
      docker rmi ${{ secrets.DH_USUARIO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      docker compose up -d traefik whoami 
      docker compose up -d api
